#!/bin/bash
set +x
set -e
. .colors.sh

BASEDIR=$PWD
. $BASEDIR/io.sh 1 1 1346 "$@"
CURDIR=`pwd`
## INPUTS VARIABLES
inputs_zip=${INPUTS1}


## PARAMETERS VARIABLES
snftemp=${PARAMS1}


set -xe

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT

cp -rv swat670 inputs/swat670
    
pushd inputs
./swat670
popd

set +x
echo -e "$(c G)[success] The model has exited with code SUCCESS"
####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
cd $BASEDIR
. $BASEDIR/output.sh